"""Add Constarint to Student Colum

Revision ID: 7426e7f0e358
Revises: f453dfc61aac
Create Date: 2023-06-28 08:32:29.755337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7426e7f0e358'
down_revision = 'f453dfc61aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
